### ISSUE TITLE
warning comments about rpc auth by cookie

### ISSUE THREAD

**Issue by LatinoMiner** [CommerciumBlockchain/cmm-node-stratum-pool#1]
The current version of z-nomp doesn't support rpc auth by cookie, so the comments below is not useful:

`# If no rpcpassword is set, rpc cookie auth is sought. The default -rpccookiefile name is .cookie and found in the -datadir being used for commerciumd. This option is typically used when the server and client are run as the same user. If not, you must set rpcuser and rpcpassword to secure the JSON-RPC api. The first method(DEPRECATED) is to set this pair for the server and client:

**Comment by anthony19114** [comment]
z-nomp must utilize auth by rpcuser and rpcpassword... which are set in the .json configuration files in pool_configs, and in the coin.conf for whichever coin daemon used.
